### Homework 2: Introduction to `numpy` and `pandas`

##### Problem 1: Import the libraries

Below, import and alias both `numpy` and `pandas` using standard alias's as we used in class.

In [1]:
import numpy as np
import pandas as pd

##### Problem 2: Create an array

Below, create a 1-Dimensional array of integer values from 0 through 100.

In [2]:
ans2 = np.arange(0, 101)
ans2.shape

(101,)

##### Problem 3: Reshape an array

Reshape the array from problem 2 so that it has 101 rows and 1 column.

In [3]:
ans3 = ans2.reshape(101, 1)
ans3.shape

(101, 1)

##### Problem 4: Create an array of 4

Below, create a 10 x 10 array filled with the value 4.  

In [4]:
ans4 = np.ones(shape = (10, 10))*4
ans4

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

##### Problem 5: Create a random array

Below, create a 4 x 8 array of values drawn from a standard normal distribution (mean = 0 and standard deviation = 1). 

In [5]:
ans5 = np.random.normal(size = (4, 8))
ans5

array([[ 0.18994243, -0.06293752,  0.67310162,  0.70581095, -1.42218113,
         0.76670656,  1.25099324, -0.63171274],
       [-1.24248517,  0.94985036, -2.86384149,  1.22382261, -1.13460352,
        -1.05593235, -0.33623623,  0.69030567],
       [-0.83174605, -0.15032863,  0.58464526, -0.08929703,  0.90045919,
        -0.59766473,  1.8920162 , -1.66903416],
       [-0.33316104,  0.22932885,  0.10332402,  1.96130945,  0.94668043,
        -0.35233156,  0.70196205, -0.28548209]])

##### Problem 6: Slicing an array

Below, create a 5 x 7 array of random values from a standard normal distribution and assign to a variable named `ans6a`.  Then, select the last two columns and last two rows of the array and assign to `ans6b`.

In [6]:
ans6a = np.random.normal(size = (5, 7))
ans6b = ans6a[-2:, -2:]
print(ans6a)
print('---------')
print(ans6b)

[[ 1.47934371 -0.15425067  0.56523698 -0.27226904 -0.76016273 -1.52599661
  -0.39720265]
 [ 0.18027319 -0.68648794 -0.80869977 -0.37379781  0.75069299 -1.96803293
   0.57937844]
 [ 1.10225984 -0.96527982  0.79671913  1.82270088 -0.51801179  1.31609962
  -0.34042897]
 [ 2.4702662   1.12401006  0.40477924  0.52540776  0.30227635 -0.82174735
   0.82765282]
 [ 1.14429835  0.97115345  0.91526732 -0.17958003  0.41725125 -0.05468031
   0.29650845]]
---------
[[-0.82174735  0.82765282]
 [-0.05468031  0.29650845]]


##### Problem 7: Mathematical Operations on an array

Below, create a 10 x 5 array of random values from a binomial distribution where `n = 1000` and `p = .3`.  Then, use `numpy` functions to find the following summary statistics for *each column*:

- mean
- variance
- standard deviation


In [7]:
ans7 = np.random.binomial(n = 1000, p = 0.3, size = (10, 5))
print(ans7.mean())
print(ans7.var())
print(ans7.std())

301.5
154.49
12.429400629153443


#### Problem 8: Using arrays in functions

Below, define a function `f` that takes a numeric input and outputs the square of that input.

Then, create a list named `x_list` and an array named `x_array` containing integers 1 - 20.  Finally, compare and discuss the difference between evaluating these functions at all integers -- `f(x_list)` and `f(x_array)`.  

In [8]:
def f(x):
    return x**2

x_list = list(range(1, 21))
x_array = np.arange(1, 21)
f(x_list)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
f(x_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [13]:
#this works how we want when the input in an array vs. that of a list
#the big idea is that arrays vectorize operations whereas we have to write a loop
#to use the list

##### Problem 9: Filtering an array

Below, use the array `ex9` and describe what happens with the comparison:

```
ex9 > 10
```

What type of objects are returned?

In [14]:
ex9 = np.random.randint(low = 8, high = 13, size = 100)

In [15]:
ex9 > 10

array([ True, False, False, False,  True, False,  True, False, False,
       False,  True,  True,  True,  True, False, False,  True, False,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False,  True,  True, False,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True, False, False,  True, False, False, False,  True,
        True, False,  True,  True,  True, False, False, False, False,
        True,  True, False, False, False, False, False,  True, False,
        True, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True,  True,  True,
       False])

##### Problem 10: Filtering an array II

Now, pass the results of the comparison to the array with

```
ex9[ex9 > 10]
```

Explain what happened.

In [16]:
ex9[ex9 > 10]

array([11, 11, 11, 12, 11, 11, 11, 12, 11, 11, 12, 11, 12, 12, 12, 11, 12,
       11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 11, 11, 11, 11, 12, 12,
       12, 11, 11, 11, 12, 12, 12])

In [17]:
#returns only where these values are true

##### Problem 11: Using `np.linalg`

Below, using the function `np.linalg.norm` to compute the distance between two vectors -- `v1` and `v2`.

Do this by looking for the norm of the vectors difference.

In [18]:
v1 = np.random.normal(size = 100)
v2 = np.random.normal(loc = 5, size = 100)

In [19]:
np.linalg.norm(v1 - v2)

51.336608117088446

##### Problem 12: Mutliplying matrices

Below, given matrices `m1` and `m2`, perform matrix muliplication using both the `np.matmul` function and the `@` shorthand.

In [20]:
m1 = np.random.normal(size = (4, 3))
m2 = np.random.normal(size = (3, 4))

In [21]:
print(np.matmul(m1, m2))
print(m1@m2)

[[-2.37626178 -3.00876735 -3.68004206 -2.56389235]
 [ 0.68098593 -1.85030931 -2.6276731  -0.59439087]
 [ 1.63532323 -2.89468843 -3.70938042 -0.92119944]
 [ 0.56877053 -0.6894286   0.34071338 -0.77321522]]
[[-2.37626178 -3.00876735 -3.68004206 -2.56389235]
 [ 0.68098593 -1.85030931 -2.6276731  -0.59439087]
 [ 1.63532323 -2.89468843 -3.70938042 -0.92119944]
 [ 0.56877053 -0.6894286   0.34071338 -0.77321522]]


##### Problem 13: Mean Squared Error

In predictive algorithms where the target is a continuous number we may use the **mean squared error** to examine the difference between true and predicted values in the model.

Below, you are given two arrays to represent a models predictions `y_pred` and true values from data `y_true`.  Use these to write a function called `mean_squared_error` that takes in two arrays and returns the mean squared error or:

$$\frac{1}{n} \sum_{i = 1}^n (\hat{y_i} - y_i)^2$$

where $\hat{y_i}$ is the prediction of the $i^{th}$ value and $y_i$ is the true value.

In [22]:
x = np.linspace(0, 10, 100)
y_true = 3*x + 4 + np.random.normal(size = 100)
y_pred = 3.2*x + 4.1

In [23]:
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

In [24]:
print(mean_squared_error(y_true, y_pred))

2.097589887986354


### Pandas

The problems below involve using the `pandas` library.

##### Problem 14: Make a `DataFrame` from `dict`

Use the dictionary `ex_14_data` to build a pandas DataFrame named `dog_df` below.

In [25]:
ex_14_data = {'name': ['Lenny', 'Hardy', 'Oden', 'Hennessy', 'Cliff'],
             'breed': ['wildman', 'lab', 'lab', 'pitbull', 'boxer'], 
             'weight': [40, 70, 65, 73, 46], 
             'age': [3, 5, 13, 15, 4]}

In [27]:
dog_df = pd.DataFrame(ex_14_data)
dog_df

name    breed  weight  age
0     Lenny  wildman      40    3
1     Hardy      lab      70    5
2      Oden      lab      65   13
3  Hennessy  pitbull      73   15
4     Cliff    boxer      46    4

##### Problem 15: Columns of a DataFrame

Below, extract the columns from the DataFrame `dog_df`.

In [28]:
dog_df.columns

Index(['name', 'breed', 'weight', 'age'], dtype='object')

##### Problem 16: Basic Information 

Use the `.info()` method to display basic information about `dog_df`.

In [29]:
dog_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   breed   5 non-null      object
 2   weight  5 non-null      int64 
 3   age     5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


#### A Second Dataset

Below, we load a built in dataset from the `seaborn` library.  We will use this library later in the course for data visualization, but for now just note that the object `titanic_df` is a DataFrame and we can just use the `.load_dataset` function to access it.

In [32]:
import seaborn as sns

In [31]:
titanic_df = sns.load_dataset('titanic')

##### Problem 17: Numerical Summaries

Use the `.describe` method to display numerical summaries for the columns in `titanic_df`.

In [33]:
titanic_df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

##### Problem 17: Categorical Summaries

Use the `.describe()` method to display summaries of *only the categorical columns*.  (**Hint**: what does the `include` argument do?)

In [34]:
titanic_df.describe(include = "object")

sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

##### Problem 18: Shape of the data

How many rows and columns are in the DataFrame `titanic_df`?

In [35]:
titanic_df.shape

(891, 15)

##### Problem 19: Summaries

What is the mean and standard deviation of the `age` column?

In [37]:
print(titanic_df['age'].mean())
print(titanic_df['age'].std())

29.69911764705882
14.526497332334044


##### Problem 20: Summaries by sex

Now, determine the mean and standard deviation for the male passengers `age`.

In [41]:
print(titanic_df.loc[titanic_df['sex'] == 'male']['age'].mean())
print(titanic_df.loc[titanic_df['sex'] == 'male']['age'].std())

30.72664459161148
14.678200823816601


##### Problem 21: Young people in first class

Subset the data to passengers under the age of 18.  How many of these passengers traveled first class?

In [43]:
titanic_df.loc[(titanic_df['age'] < 18) & (titanic_df['pclass'] == 1)].shape[0]

12

##### Problem 22: Older people embarked

Subset the data `titanic_df` to people over the age of 70.  What was the most common point of departure for them (`embark_town`)?

In [45]:
titanic_df.loc[titanic_df['age'] > 70, ['embark_town']].value_counts()

embark_town
Cherbourg      2
Southampton    2
Queenstown     1
dtype: int64

##### Problem 23: Survival Rate

Use the `survived` column to compute the survival rate for all passengers.

In [46]:
titanic_df['survived'].value_counts(normalize = True)

0    0.616162
1    0.383838
Name: survived, dtype: float64

In [47]:
titanic_df['survived'].mean()

0.3838383838383838

##### Problem 24: Renaming Columns

Rename the column `sibsp` to `num_siblings`.  

In [50]:
titanic_df.rename({'sibsp': 'num_siblings'}, axis = 1, inplace = True)

##### Problem 25: Dropping Columns

Drop the column `adult_male` from `titanic_df`.  

In [52]:
titanic_df.drop('adult_male', axis = 1, inplace = True)

In [53]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   survived      891 non-null    int64   
 1   pclass        891 non-null    int64   
 2   sex           891 non-null    object  
 3   age           714 non-null    float64 
 4   num_siblings  891 non-null    int64   
 5   parch         891 non-null    int64   
 6   fare          891 non-null    float64 
 7   embarked      889 non-null    object  
 8   class         891 non-null    category
 9   who           891 non-null    object  
 10  deck          203 non-null    category
 11  embark_town   889 non-null    object  
 12  alive         891 non-null    object  
 13  alone         891 non-null    bool    
dtypes: bool(1), category(2), float64(2), int64(4), object(5)
memory usage: 79.8+ KB


#### Code Wars

It is important to continue practicing the fundamentals as we move into using more and more libraries.  You will always need to fall back on the basics, so we want you to spend time each week working on some coding challenges.  Again, head over to [code wars]() and find two practice problems that you are able to solve. Clearly state the problem, your solution, and an alternative solution that you didn't think of but was displayed upon cracking your challenge below.